### PR TITLE
Longformer medium article summary

### PR DESCRIPTION
**Pull request by Viktor2k**

### CODE REVIEW

**Comment by omarsar** [comment]
@Viktor2k do you mind if I add you as a maintainer here? That way, you can help us with other PRs and be able to also submit and merge yours. Thanks.

**Comment by Viktor2k** [comment]
@omarsar Sure! Glad to keep this process going :)

**Comment by omarsar** [comment]
@e-tony do we have this Longformer summary in the list?

**Comment by e-tornike** [comment]
No, I it isn't. We can merge.

**Pull request merged**
