### PR TITLE
Tldr contribution

### PR DESCRIPTION
**Pull request by Viktor2k**
Great initiative with this repository. I have myself kind of the same view regarding the potential benefits of paper summaries, both for me and others, as you have. 

I hope these summaries (SentenceBERT, DistillBERT and an example usecase of semantic search utilizing SentenceBERT) live up to the standard you expect :)

### CODE REVIEW

**Comment by omarsar** [comment]
@Viktor2k I really appreciate your comments and your interest to contribute here. I checked the links and they are very nice summaries that would fit well here. However, I am not sure if those articles will be accessible by everyone given that the articles have the distributed setting enabled on Medium. 

We are really trying hard to ensure that we point to articles that are accessible to as many people as possible. Do you have these articles hosted in other places, like a website or blog?

In some cases, we have even asked authors to grant us permission to repost their articles on our website just to make sure readers have that option. I know a lot of readers still use Medium, so I wouldn't mind pointing them to the original Medium article but having an alternate link does help. I hope you can understand.

**Comment by Viktor2k** [comment]
Thanks for appreciating my work. I do, unfortunately, not have any other blog where these articles are posted but would be alright with posting it on your website with a reference to the original medium article. Is that a posibility?

**Comment by omarsar** [comment]
@Viktor2k yes, we provide the reference to the original. Do you mind sending me a 2-3 sentence bio to include as well? 

@angysaravia we are reposting these articles to the main website and include the links to this repo.

**Comment by Viktor2k** [comment]
@omarsar Perfect! 

Here's my bio: Machine Learning Engineer with a growing interest of NLP. Trying to stay on-top of recent developments within the ML field in general, and NLP in particular, with the goal of sharing knowledge and understanding to a wider audience. 

When can i expect the article to be published?

**Comment by omarsar** [comment]
@Viktor2k Thanks. We should have them ready in the coming week. I will keep you posted. :)

**Comment by omarsar** [comment]
@Viktor2k the changes have been made. Your articles have been added to the website as well. I changed the links in this repo myself. You can check the repo. Thanks again for doing this. I am sure this is going to be useful for so many learners. Let me know if you have any questions. 

I am merging this.

**Pull request merged**
