### PR TITLE
summary contribution: Tiny BERT with reference to medium

### PR DESCRIPTION
**Pull request by Viktor2k**
My contributions continue and with that I'm wondering how we can make it as smooth as possible. Previous articles were copied over to dair.ai with references to the originial, medium article. Is that how we should deal with this one too?

### CODE REVIEW

**Comment by omarsar** [comment]
@Viktor2k Yes, the same applies. I hope you don't mind. Congrats on these articles, they are very well written. I really like them and they have been getting a lot of attention on the site. I will keep pushing them here, our website, social media, and in the case of relatively new articles like this one, the NLP Newsletter as well. I really appreciate your contributions here. We will take of the migrations. We have people helping with that so in the future, all you need to do is to leave a comment (granting permission to report) as you did on this one. This only applies to Medium articles that have distributed setting on. Thanks!

**Comment by Viktor2k** [comment]
Thanks! Really encouraging to hear this! :) Is there some way I could take part of those reader numbers? Further, would it be possible for me to publish future articles in the Dair.ai Medium publication?

**Comment by omarsar** [comment]
@Viktor2k We can definitely consider publishing on the dair.ai Medium publication directly. This makes sense because paper summaries encompass most of the content there and that's what most of our readers are looking for. We also help to repost on the main site as well, this increases the accessibility and exposure to the article.

Keep in mind that all our publications on Medium should be accessible to everyone which means that our articles are kept open and we need to keep the distribution option disabled before publishing.

If that makes sense, please feel free to join our Slack group [here](https://join.slack.com/t/dairai/shared_invite/zt-d2srv503-bQ01ZPLC4t4OoolEN9saSg) so that we can better collaborate on these summaries.

**Comment by Viktor2k** [comment]
@omarsar Perfect! I'll write some TLDR's for the articles i've already published and add these to the dair.ai publication on medium and as .md files for this repo! Please add me to the publication whenever you have time! :)

**Comment by Viktor2k** [comment]
TinyBERT TLDR added. Will post the same one to the dair.ai publication as soon as I can! :)

**Comment by omarsar** [comment]
Hi @Viktor2k maybe I didn't communicate something clearly above. TLDRs are okay to publish on GitHub and they are something we need more of in this repository. What we are seeking to publish on the dair.ai publications are longer form paper summaries as the originals you have been writing. 

Some examples:

https://medium.com/dair-ai/research/home

Thanks again for your contributions.

I have helped our group pick out some interesting papers to write summaries on but you can work on any you prefer or find interesting. 

https://github.com/dair-ai/dair-ai.github.io/issues/27

**Comment by Viktor2k** [comment]
@omarsar Oh I see! I'll still publish the TLDR here then and wait with medium articles until i have something more thorough. Actually started summarizing "Longformer" yesterday (which i also saw was available [here](dair-ai/dair-ai.github.io#27)) as I got inspired from the newsletter!

**Pull request closed without merging**
